import { db } from '../db';
import { makeId } from './ids';
import type { Category, GearItem } from '../types/models';

export async function seedDemoData(categories: Category[]) {
  const now = new Date().toISOString();
  const findCategory = (namePart: string) =>
    categories.find((c) => c.name.toLowerCase().includes(namePart.toLowerCase()))?.id ?? categories[0]?.id;

  const gear: GearItem[] = [
    // ========== CAMERA BODIES (5 items) ==========
    {
      id: makeId(),
      name: 'Sony FX30',
      categoryId: findCategory('camera') ?? 'default-1',
      brand: 'Sony',
      model: 'FX30',
      condition: 'new',
      quantity: 1,
      tags: ['video', 'cinema', 'corporate'],
      essential: true,
      inferredProfile: 'video_first',
      capabilities: ['4K 120fps', '10-bit 4:2:2 internal', 'S-Cinetone', 'dual base ISO', 'APS-C sensor'],
      eventFit: ['corporate', 'interview', 'documentary', 'music-video', 'real-estate', 'indoor', 'run-and-gun'],
      strengths: ['cinematic-look', 'low-light', 'autofocus', 'mount-sony-e', 'dual-card-slots'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony A7 IV',
      categoryId: findCategory('camera') ?? 'default-1',
      brand: 'Sony',
      model: 'A7 IV',
      condition: 'new',
      quantity: 1,
      tags: ['hybrid', 'wedding', 'versatile'],
      essential: true,
      inferredProfile: 'hybrid',
      capabilities: ['33MP photos', '4K 60fps video', 'excellent autofocus', 'dual card slots', 'balanced photo/video'],
      eventFit: ['wedding', 'portrait', 'event', 'travel', 'outdoor', 'indoor'],
      strengths: ['mid-range', 'high-resolution', 'autofocus', 'low-light', 'mount-sony-e', 'dual-card-slots'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Canon R5',
      categoryId: findCategory('camera') ?? 'default-1',
      brand: 'Canon',
      model: 'EOS R5',
      condition: 'new',
      quantity: 1,
      tags: ['photo', 'high-res', 'wedding'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['45MP photos', '8K video', 'in-body stabilization', 'animal eye-AF', 'dual card slots'],
      eventFit: ['wedding', 'portrait', 'event', 'studio', 'outdoor'],
      strengths: ['high-resolution', 'autofocus', 'mount-canon-rf', 'dual-card-slots', 'silent-operation'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony A7S III',
      categoryId: findCategory('camera') ?? 'default-1',
      brand: 'Sony',
      model: 'A7S III',
      condition: 'good',
      quantity: 1,
      tags: ['video', 'low-light', 'cinematic'],
      essential: false,
      inferredProfile: 'video_first',
      capabilities: ['4K 120fps', 'exceptional low-light', '10-bit 4:2:2', 'full-frame sensor', 'dual base ISO'],
      eventFit: ['corporate', 'interview', 'documentary', 'music-video', 'low-light', 'indoor', 'wedding'],
      strengths: ['cinematic-look', 'low-light', 'autofocus', 'mount-sony-e', 'dual-card-slots'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Fujifilm X-T5',
      categoryId: findCategory('camera') ?? 'default-1',
      brand: 'Fujifilm',
      model: 'X-T5',
      condition: 'new',
      quantity: 1,
      tags: ['photo', 'travel', 'compact'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['40MP APS-C', 'film simulations', 'compact body', 'in-body stabilization', '6K video'],
      eventFit: ['portrait', 'travel', 'outdoor', 'event', 'studio'],
      strengths: ['high-resolution', 'portability', 'weather-sealed', 'mount-fuji-x'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== LENSES (10 items) ==========
    {
      id: makeId(),
      name: 'Tamron 17-28mm f/2.8',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Tamron',
      model: '17-28mm f/2.8 Di III RXD',
      condition: 'new',
      quantity: 1,
      tags: ['wide', 'video', 'compact'],
      essential: true,
      inferredProfile: 'hybrid',
      capabilities: ['ultra-wide zoom', 'f/2.8 constant aperture', 'compact and light', 'video-optimized'],
      eventFit: ['corporate', 'interview', 'real-estate', 'travel', 'indoor', 'outdoor'],
      strengths: ['wide-angle', 'fast-aperture', 'low-light', 'portability', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony 24-70mm f/2.8 GM II',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sony',
      model: 'FE 24-70mm f/2.8 GM II',
      condition: 'new',
      quantity: 1,
      tags: ['versatile', 'wedding', 'workhorse'],
      essential: true,
      inferredProfile: 'hybrid',
      capabilities: ['versatile zoom', 'f/2.8 constant', 'excellent sharpness', 'fast autofocus'],
      eventFit: ['wedding', 'portrait', 'event', 'corporate', 'indoor', 'outdoor'],
      strengths: ['mid-range', 'fast-aperture', 'low-light', 'autofocus', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony 70-200mm f/2.8 GM II',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sony',
      model: 'FE 70-200mm f/2.8 GM II',
      condition: 'new',
      quantity: 1,
      tags: ['telephoto', 'wedding', 'events'],
      essential: false,
      inferredProfile: 'hybrid',
      capabilities: ['telephoto zoom', 'f/2.8 constant', 'compression', 'event coverage'],
      eventFit: ['wedding', 'portrait', 'event', 'sports', 'outdoor'],
      strengths: ['telephoto', 'fast-aperture', 'low-light', 'shallow-dof', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sigma 35mm f/1.4 DG DN',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sigma',
      model: '35mm f/1.4 DG DN Art',
      condition: 'good',
      quantity: 1,
      tags: ['prime', 'low-light', 'documentary'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['f/1.4 aperture', 'natural FOV', 'exceptional sharpness', 'shallow DOF'],
      eventFit: ['wedding', 'portrait', 'documentary', 'low-light', 'indoor'],
      strengths: ['fast-aperture', 'low-light', 'shallow-dof', 'portability', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony 85mm f/1.8',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sony',
      model: 'FE 85mm f/1.8',
      condition: 'new',
      quantity: 1,
      tags: ['portrait', 'bokeh', 'headshots'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['portrait focal length', 'f/1.8 aperture', 'flattering compression', 'shallow DOF'],
      eventFit: ['portrait', 'wedding', 'event', 'studio', 'indoor', 'outdoor'],
      strengths: ['telephoto', 'fast-aperture', 'shallow-dof', 'portability', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Canon RF 50mm f/1.2 L',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Canon',
      model: 'RF 50mm f/1.2 L USM',
      condition: 'new',
      quantity: 1,
      tags: ['prime', 'low-light', 'portrait'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['f/1.2 aperture', 'exceptional low-light', 'beautiful bokeh', 'professional build'],
      eventFit: ['portrait', 'wedding', 'low-light', 'indoor', 'studio', 'event'],
      strengths: ['fast-aperture', 'low-light', 'shallow-dof', 'autofocus', 'mount-canon-rf'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Fujifilm 16-55mm f/2.8',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Fujifilm',
      model: 'XF 16-55mm f/2.8 R LM WR',
      condition: 'good',
      quantity: 1,
      tags: ['zoom', 'weather-sealed', 'travel'],
      essential: false,
      inferredProfile: 'hybrid',
      capabilities: ['standard zoom', 'f/2.8 constant', 'weather-sealed', 'versatile range'],
      eventFit: ['portrait', 'travel', 'outdoor', 'event', 'wedding'],
      strengths: ['mid-range', 'fast-aperture', 'weather-sealed', 'portability', 'mount-fuji-x'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sony 16-35mm f/4 PZ G',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sony',
      model: 'FE 16-35mm f/4 PZ G',
      condition: 'new',
      quantity: 1,
      tags: ['wide', 'video', 'powered-zoom'],
      essential: false,
      inferredProfile: 'video_first',
      capabilities: ['ultra-wide zoom', 'powered zoom for video', 'compact design', 'constant f/4'],
      eventFit: ['real-estate', 'travel', 'outdoor', 'corporate', 'documentary', 'run-and-gun'],
      strengths: ['wide-angle', 'portability', 'mount-sony-e', 'silent-operation'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Sigma 105mm f/2.8 Macro',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Sigma',
      model: '105mm f/2.8 DG DN Macro',
      condition: 'new',
      quantity: 1,
      tags: ['macro', 'product', 'detail'],
      essential: false,
      inferredProfile: 'photo_first',
      capabilities: ['1:1 macro', '105mm focal length', 'f/2.8 aperture', 'detail capture'],
      eventFit: ['product-shoot', 'wedding', 'portrait', 'studio', 'indoor'],
      strengths: ['macro', 'shallow-dof', 'telephoto', 'mount-sony-e'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Canon RF 24-105mm f/4 L',
      categoryId: findCategory('lenses') ?? 'default-2',
      brand: 'Canon',
      model: 'RF 24-105mm f/4 L IS USM',
      condition: 'good',
      quantity: 1,
      tags: ['zoom', 'versatile', 'travel'],
      essential: false,
      inferredProfile: 'hybrid',
      capabilities: ['versatile zoom range', 'constant f/4', 'image stabilization', 'all-purpose'],
      eventFit: ['travel', 'event', 'portrait', 'wedding', 'outdoor', 'indoor'],
      strengths: ['mid-range', 'telephoto', 'portability', 'mount-canon-rf'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== AUDIO (3 items) ==========
    {
      id: makeId(),
      name: 'Rode Wireless Go II',
      categoryId: findCategory('audio') ?? 'default-6',
      brand: 'Rode',
      model: 'Wireless Go II',
      condition: 'new',
      quantity: 1,
      tags: ['wireless', 'lav', 'interview'],
      essential: false,
      inferredProfile: 'audio',
      capabilities: ['dual-channel wireless', 'built-in recording', 'lavalier mics', 'compact design'],
      eventFit: ['interview', 'corporate', 'documentary', 'wedding', 'run-and-gun', 'event'],
      strengths: ['close-mic', 'wireless', 'portability', 'compact'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Rode VideoMic NTG',
      categoryId: findCategory('audio') ?? 'default-6',
      brand: 'Rode',
      model: 'VideoMic NTG',
      condition: 'new',
      quantity: 1,
      tags: ['shotgun', 'on-camera', 'directional'],
      essential: false,
      inferredProfile: 'audio',
      capabilities: ['shotgun mic', 'on-camera mount', 'directional audio', 'broadcast quality'],
      eventFit: ['corporate', 'interview', 'documentary', 'run-and-gun', 'outdoor', 'event'],
      strengths: ['directional-audio', 'portability', 'compact'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Zoom H6 Recorder',
      categoryId: findCategory('audio') ?? 'default-6',
      brand: 'Zoom',
      model: 'H6',
      condition: 'good',
      quantity: 1,
      tags: ['recorder', 'backup', 'multi-track'],
      essential: false,
      inferredProfile: 'audio',
      capabilities: ['6-track recording', 'interchangeable capsules', 'backup recorder', 'professional audio'],
      eventFit: ['interview', 'documentary', 'event', 'corporate'],
      strengths: ['multi-track', 'rugged', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== LIGHTING (4 items) ==========
    {
      id: makeId(),
      name: 'Godox SL-60W',
      categoryId: findCategory('lighting') ?? 'default-4',
      brand: 'Godox',
      model: 'SL-60W',
      condition: 'new',
      quantity: 1,
      tags: ['led', 'continuous', 'video'],
      essential: false,
      inferredProfile: 'lighting',
      capabilities: ['60W LED', 'continuous light', 'Bowens mount', 'video-optimized'],
      eventFit: ['corporate', 'interview', 'product-shoot', 'studio', 'indoor', 'real-estate'],
      strengths: ['continuous-light', 'powered-light'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Aputure MC Pro',
      categoryId: findCategory('lighting') ?? 'default-4',
      brand: 'Aputure',
      model: 'MC Pro',
      condition: 'new',
      quantity: 2,
      tags: ['rgb', 'compact', 'portable'],
      essential: false,
      inferredProfile: 'lighting',
      capabilities: ['compact RGB LED', 'magnetic mount', 'app control', 'bi-color + RGB'],
      eventFit: ['corporate', 'interview', 'product-shoot', 'music-video', 'indoor', 'run-and-gun'],
      strengths: ['continuous-light', 'powered-light', 'wireless', 'compact', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Godox V1 Flash',
      categoryId: findCategory('lighting') ?? 'default-4',
      brand: 'Godox',
      model: 'V1',
      condition: 'new',
      quantity: 1,
      tags: ['flash', 'wedding', 'ttl'],
      essential: false,
      inferredProfile: 'lighting',
      capabilities: ['round head flash', 'TTL support', 'magnetic modifiers', 'fast recycling'],
      eventFit: ['wedding', 'portrait', 'event', 'indoor', 'studio'],
      strengths: ['flash-strobe', 'powered-light', 'wireless', 'fast-charging'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: '5-in-1 Reflector',
      categoryId: findCategory('lighting') ?? 'default-4',
      brand: 'Neewer',
      model: '43" 5-in-1',
      condition: 'good',
      quantity: 1,
      tags: ['reflector', 'natural-light', 'outdoor'],
      essential: false,
      inferredProfile: 'lighting',
      capabilities: ['5 surfaces', 'collapsible design', 'natural light modifier', 'portable'],
      eventFit: ['portrait', 'outdoor', 'wedding', 'travel', 'event'],
      strengths: ['natural-light-modifier', 'portability', 'compact'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== SUPPORT (3 items) ==========
    {
      id: makeId(),
      name: 'Manfrotto 190 Tripod',
      categoryId: findCategory('tripods') ?? 'default-3',
      brand: 'Manfrotto',
      model: 'MT190XPRO4',
      condition: 'good',
      quantity: 1,
      tags: ['tripod', 'stable', 'aluminum'],
      essential: false,
      inferredProfile: 'support',
      capabilities: ['aluminum tripod', 'stable platform', 'video fluid head compatible', 'professional build'],
      eventFit: ['corporate', 'interview', 'real-estate', 'product-shoot', 'studio', 'event'],
      strengths: ['static-support', 'rugged'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Peak Design Travel Tripod',
      categoryId: findCategory('tripods') ?? 'default-3',
      brand: 'Peak Design',
      model: 'Travel Tripod Carbon',
      condition: 'new',
      quantity: 1,
      tags: ['compact', 'travel', 'lightweight'],
      essential: false,
      inferredProfile: 'support',
      capabilities: ['ultra-compact design', 'carbon fiber', 'travel-optimized', 'integrated head'],
      eventFit: ['travel', 'outdoor', 'portrait', 'wedding', 'run-and-gun'],
      strengths: ['static-support', 'portability', 'weather-sealed', 'compact'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'DJI RS 3 Pro Gimbal',
      categoryId: findCategory('tripods') ?? 'default-3',
      brand: 'DJI',
      model: 'RS 3 Pro',
      condition: 'new',
      quantity: 1,
      tags: ['gimbal', 'video', 'stabilization'],
      essential: false,
      inferredProfile: 'support',
      capabilities: ['3-axis gimbal', 'cinema camera support', 'ActiveTrack', 'smooth video'],
      eventFit: ['corporate', 'music-video', 'documentary', 'run-and-gun', 'wedding', 'event', 'real-estate', 'travel'],
      strengths: ['smooth-motion', 'wireless', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== POWER (2 items) ==========
    {
      id: makeId(),
      name: 'NP-FZ100 Batteries',
      categoryId: findCategory('power') ?? 'default-8',
      brand: 'Sony',
      model: 'NP-FZ100',
      condition: 'new',
      quantity: 6,
      tags: ['battery', 'essential', 'spare'],
      essential: true,
      inferredProfile: 'power',
      capabilities: ['Sony camera battery', 'long runtime', 'high capacity', 'spare power'],
      eventFit: ['wedding', 'corporate', 'interview', 'event', 'travel', 'documentary', 'music-video', 'real-estate', 'portrait'],
      strengths: ['long-battery-life', 'portability', 'fast-charging'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'Anker 737 Power Bank',
      categoryId: findCategory('power') ?? 'default-8',
      brand: 'Anker',
      model: '737 PowerCore 24K',
      condition: 'new',
      quantity: 1,
      tags: ['power-bank', 'usb-c', 'backup'],
      essential: false,
      inferredProfile: 'power',
      capabilities: ['24000mAh capacity', 'USB-C PD', 'multiple ports', 'fast charging'],
      eventFit: ['wedding', 'corporate', 'travel', 'outdoor', 'run-and-gun', 'event', 'music-video', 'real-estate', 'portrait'],
      strengths: ['long-battery-life', 'portability', 'fast-charging'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== MEDIA (2 items) ==========
    {
      id: makeId(),
      name: 'CFexpress Type A 160GB',
      categoryId: findCategory('media') ?? 'default-9',
      brand: 'Sony',
      model: 'CEA-G160T',
      condition: 'new',
      quantity: 3,
      tags: ['fast', 'video', 'recording'],
      essential: true,
      inferredProfile: 'media',
      capabilities: ['CFexpress Type A', '800 MB/s read', '700 MB/s write', 'video-optimized'],
      eventFit: ['corporate', 'interview', 'documentary', 'music-video', 'wedding', 'event', 'real-estate', 'portrait', 'travel'],
      strengths: ['high-speed', 'rugged', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: makeId(),
      name: 'SD UHS-II 128GB',
      categoryId: findCategory('media') ?? 'default-9',
      brand: 'SanDisk',
      model: 'Extreme Pro UHS-II',
      condition: 'new',
      quantity: 4,
      tags: ['sd-card', 'backup', 'photo'],
      essential: true,
      inferredProfile: 'media',
      capabilities: ['128GB UHS-II', 'fast read/write', 'dual slot backup', 'reliable storage'],
      eventFit: ['wedding', 'portrait', 'event', 'travel', 'outdoor', 'indoor', 'corporate', 'music-video'],
      strengths: ['high-speed', 'rugged', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },

    // ========== ACCESSORIES (1 item) ==========
    {
      id: makeId(),
      name: 'Peak Design Everyday Backpack',
      categoryId: findCategory('bags') ?? 'default-10',
      brand: 'Peak Design',
      model: 'Everyday Backpack 30L V2',
      condition: 'new',
      quantity: 1,
      tags: ['bag', 'travel', 'protection'],
      essential: true,
      inferredProfile: 'accessory',
      capabilities: ['30L capacity', 'customizable dividers', 'weather-resistant', 'laptop compartment'],
      eventFit: ['travel', 'wedding', 'outdoor', 'run-and-gun', 'event', 'documentary'],
      strengths: ['weather-sealed', 'portability'],
      classificationStatus: 'done',
      createdAt: now,
      updatedAt: now,
    },
  ];

  await db.transaction('rw', db.gearItems, async () => {
    await db.gearItems.bulkAdd(gear);
  });
}

export async function removeDemoData() {
  await db.transaction('rw', db.gearItems, db.events, async () => {
    await db.gearItems.clear();
    await db.events.clear();
  });
}
